### ISSUE TITLE
Caminhamento em Profundidade

### ISSUE THREAD

**Issue by Piazzi** [Piazzi/grafos-subconjunto-independente#18]
- [x] Implementar um algoritmo que faça um caminhamento em profundidade do grafo solicitado.
- [x] Printar o caminhamento.
- [x] Adicionar a opção "Caminhamento em Profundidade" no menu principal.

**Comment by vitorqcq** [comment]
Comecei a implementar um caminhamento em profundidade , mas ainda não acabei (deixei como comentário)
